# Generated by Django 2.2.3 on 2020-01-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='caminho',
            field=models.ImageField(upload_to='images/', verbose_name='caminho'),
        ),
    ]
