# Generated by Django 2.2.3 on 2020-01-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200128_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='imagem',
            field=models.OneToOneField(on_delete='cascade', to='core.Imagem'),
        ),
    ]
